paths:
  /notifications/markAllAsRead:
    post:
      tags:
        - Notifications
      summary: Mark all notifications as read
      responses:
        200:
          description: All user's notifications marked as read
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Response message

        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

  /notifications:
    get:
      tags:
        - Notifications
      summary: Get all user's notifications
      responses:
        200:
          description: Fetched all notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Notification"
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

  /notifications/{id}:
    post:
      tags:
        - Notifications
      summary: Mark specific notification as read
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Notification marked as read
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Response message
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

components:
  schemas:
    Notification:
      type: object
      properties:
        notification_id:
          type: string
        message:
          type: string
        type:
          type: string
        note_id:
          type: string
        isRead:
          type: string
        time_created:
          type: string
        time_read:
          type: string
