paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      responses:
        200:
          description: All user's notifications marked as read
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

  /user/{id}:
    get:
      tags:
        - Users
      summary: Get all user's notifications
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Fetched all notifications
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

  /user:
    put:
      tags:
        - Users
      summary: Create a new user
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uid:
                  type: string
                  description: uid of the user
                name:
                  type: string
                  description: user name
                email:
                  type: string
                  description: user email
      responses:
        200:
          description: Notification marked as read
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Response message
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        profile_picture:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
